In [66]:
import pandas as pd
from glob import glob
import processor
import bioframe as bf
import numpy as np
import bioframe.vis
import matplotlib.pyplot as plt
import pysam

In [6]:
data_path = '/scratch/groups/horence/angelika/EM_expression/data/'
processed_path = './processed_files/'

In [64]:
bams_path = '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/*/2Aligned.out.bam'

In [65]:
bam_files = glob(bams_path)
bam_files

['/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_bladder_2_S8_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_lung_3_S12_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_endopancreas_1_S1_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_blood_1_S16_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_muscle_3_S15_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_bladder_3_S9_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_blood_3_S18_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_exopancreas2_2_S5_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_exopancreas1_1_S19_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_exopancreas1_2_S20_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_bladder_2_S8_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_lung_2_S11_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_muscle_3_S15_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_lung_3_S12_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_lung_2_S11_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_exopancreas2_3_S6_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_endopancreas_2_S2_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_exopancreas2_3_S6_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_exopancreas2_1_S4_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_endopancreas_2_S2_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_lung_1_S10_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_exopancreas1_2_S20_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_exopancreas1_3_S21_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_endopancreas_3_S3_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_lung_1_S10_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_bladder_3_S9_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_blood_2_S17_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_muscle_2_S14_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_bladder_1_S7_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_bladder_1_S7_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_muscle_1_S13_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_exopancreas1_3_S21_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_blood_3_S18_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_blood_1_S16_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_endopancreas_1_S1_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_exopancreas1_1_S19_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_exopancreas2_2_S5_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_exopancreas2_1_S4_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_muscle_1_S13_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_muscle_2_S14_L004/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_endopancreas_3_S3_L003/2Aligned.out.bam',
 '/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_blood_2_S17_L003/2Aligned.out.bam']

In [35]:
matrices_paths = glob(processed_path+'E*')

In [36]:
matrices_paths

['./processed_files/ENSG00000122068.13.tsv',
 './processed_files/ENSG00000274276.4.tsv',
 './processed_files/ENSG00000241860.7.tsv',
 './processed_files/ENSG00000129484.14.tsv',
 './processed_files/ENSG00000225138.8.tsv',
 './processed_files/ENSG00000228463.10.tsv',
 './processed_files/ENSG00000180902.18.tsv']

In [37]:
k = 2
matrix_df = pd.read_csv(matrices_paths[k], sep='\t')
matrix_df

  chrom   start     end  exon_0  exon_1  exon_2  exon_3  exon_4
0  chr1  141474  143011       1       0       0       0       0
1  chr1  146386  149707       1       1       0       0       0
2  chr1  155767  155831       0       1       0       0       0
3  chr1  164263  164791       0       1       0       0       0
4  chr1  165491  165942       0       1       1       1       0
5  chr1  167129  168165       0       1       1       1       1
6  chr1  168610  168767       0       0       0       1       0
7  chr1  169049  169264       0       1       1       0       1
8  chr1  172557  172688       0       1       0       0       0
9  chr1  173753  173862       0       1       0       0       0

In [38]:
# matrices_paths = glob(processed_path+'E*')

In [39]:
bam_files[j]

'/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_blood_1_S16_L003/2Aligned.out.bam'

In [53]:
bam_files[j][:-8]

'/scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_bladder_3_S9_L004/2Aligned'

In [61]:
import pysam
j=0

index_filename = bam_files[j][:-4]+'.sorted.bam.bai'
samfile = pysam.AlignmentFile(bam_files[j], mode="rb", index_filename=index_filename)
for read in samfile.fetch('chr1', 100, 120):
    print(read)

samfile.close()

[W::hts_idx_load3] The index file is older than the data file: /scratch/groups/horence/Roozbeh/single_cell_project/output/TSP1_10X_redo/TSP1_bladder_2_S8_L004/2Aligned.out.sorted.bam.bai
[E::bgzf_read_block] Invalid BGZF header at offset 7787
[E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes

OSError: truncated file

In [67]:
j=0
sorted_name = bam_files[j][:-4]+'.sorted.bam'
pysam.sort("-o", sorted_name, bam_files[j])

''

In [70]:
j = 0
start, end = matrix_df.iloc[0].start, matrix_df.iloc[-1].end
chrom = matrix_df.iloc[0].chrom
reads_df = bf.read_bam(sorted_name, chrom=chrom, start=start, end=end, )

In [71]:
reads_df

,QNAME,FLAG,RNAME,POS,MAPQ,CIGAR,RNEXT,PNEXT,TLEN,SEQ,QUAL,TAGs
0,A00111:327:HL57HDSXX:4:2560:5936:8171_CGTGTCTA...,272,0,14769,0,NaN,-1,-1,0,ACACGCGGGCAAAGGCTCCTCCGGGCCCCTCACCAGCCCCAGGTCC...,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,"{""NH"": 6, ""HI"": 4, ""AS"": 89, ""nM"": 0, ""NM"": 0,..."
1,A00111:327:HL57HDSXX:4:2560:5565:8656_CGTGTCTA...,272,0,14769,0,NaN,-1,-1,0,ACACGCGGGCAAAGGCTCCTCCGGGCCCCTCACCAGCCCCAGGTCC...,"FFFFFFFFF,FF,FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...","{""NH"": 6, ""HI"": 4, ""AS"": 89, ""nM"": 0, ""NM"": 0,..."
2,A00111:327:HL57HDSXX:4:2219:28022:11788_AGCCAC...,272,0,14797,0,NaN,-1,-1,0,CTCACCAGCCCCAGGTCCTTTCCCAGAGATGCCTTGCTCCTGCTCC...,FFF:FFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFF...,"{""NH"": 7, ""HI"": 2, ""AS"": 74, ""nM"": 0, ""NM"": 0,..."
3,A00111:327:HL57HDSXX:4:2309:6280:13182_ACGTTCC...,272,0,14802,0,NaN,-1,-1,0,CAGCCCCAGGTCCTTTCCCAGAGATGCCTTGCTCCTGCTCCTTCTG...,"FF:F::FFFFFFFFFFFFFFFFFFF,F:FFFFFFFFFFFF:FF,FF...","{""NH"": 7, ""HI"": 4, ""AS"": 89, ""nM"": 0, ""NM"": 0,..."
4,A00111:327:HL57HDSXX:4:1157:9317:2910_GAGTTTGA...,272,0,24847,0,NaN,-1,-1,0,CTGACCTGCCAGGGAGTGCTGCATCCTCACAGGAGTCATGGTGCCG...,FFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFF...,"{""NH"": 6, ""HI"": 5, ""AS"": 64, ""nM"": 0, ""NM"": 0,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
450,A00111:327:HL57HDSXX:4:1271:28067:9674_GGAGCAA...,272,0,172260,0,NaN,-1,-1,0,GCCCAAGCCAGGGGCAGGAAGCTAAACTGATGCCTAGGGTAATCCC...,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,"{""NH"": 10, ""HI"": 6, ""AS"": 89, ""nM"": 0, ""NM"": 0..."
451,A00111:327:HL57HDSXX:4:2677:5159:31845_CGGGTGT...,272,0,172263,0,NaN,-1,-1,0,CAAGCCAGGGGCAGGAAGCTAAACTGATGCCTAGGGTAATCCCAAC...,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,"{""NH"": 10, ""HI"": 6, ""AS"": 89, ""nM"": 0, ""NM"": 0..."
452,A00111:327:HL57HDSXX:4:1662:28845:23422_GATAGA...,272,0,172292,0,NaN,-1,-1,0,CCTAGGGTAATCCCAACAAAGTCCCTGGTTCCCCGCAGCTATGGGG...,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,"{""NH"": 10, ""HI"": 4, ""AS"": 89, ""nM"": 0, ""NM"": 0..."
453,A00111:327:HL57HDSXX:4:2502:2465:10363_GATTCGA...,272,0,172296,0,NaN,-1,-1,0,GGGTAATCCCAACAAAGTCCCTGGTTCCCCGCAGCTATGGGGCTGA...,"FFFFFFFFF:FFF:,FF,FFF:FF,FF:FFFFFFF,FFFFFFFFFF...","{""NH"": 10, ""HI"": 4, ""AS"": 87, ""nM"": 1, ""NM"": 1..."
454,A00111:327:HL57HDSXX:4:2160:9019:35493_TGTGAGC...,256,0,172622,0,NaN,-1,-1,0,GGCATGAGGCGTGCCCAGAGGGACAGAGGCAGATGAGTTTCGTCTC...,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,"{""NH"": 7, ""HI"": 1, ""AS"": 90, ""nM"": 0, ""NM"": 0,..."