In [4]:
import bioframe as bf
import pandas as pd
from glob import glob

In [5]:
data_path = '/scratch/groups/horence/angelika/EM_expression/data/'

In [6]:
glob(data_path+'*')

['/scratch/groups/horence/angelika/EM_expression/data/iso',
 '/scratch/groups/horence/angelika/EM_expression/data/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_exon_reads.parquet',
 '/scratch/groups/horence/angelika/EM_expression/data/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.gct.gz',
 '/scratch/groups/horence/angelika/EM_expression/data/gencode.v38.annotation.gff3.gz',
 '/scratch/groups/horence/angelika/EM_expression/data/GTEx_Analysis_2017-06-05_v8_STARv2.5.3a_junctions.gct.gz']

In [9]:
mrna = bf.UCSCClient('hg38').fetch_mrna()

In [11]:
mrna.columns

Index(['bin', 'matches', 'misMatches', 'repMatches', 'nCount', 'qNumInsert',
       'qBaseInsert', 'tNumInsert', 'tBaseInsert', 'strand', 'qName', 'qSize',
       'qStart', 'qEnd', 'tName', 'tSize', 'tStart', 'tEnd', 'blockCount',
       'blockSizes', 'qStarts', 'tStarts'],
      dtype='object')

In [14]:
mrna

,bin,matches,misMatches,repMatches,nCount,qNumInsert,qBaseInsert,tNumInsert,tBaseInsert,strand,...,qStart,qEnd,tName,tSize,tStart,tEnd,blockCount,blockSizes,qStarts,tStarts
0,585,1579,25,0,0,0,0,2,884,+,...,0,1604,chr1,248956422,11873,14361,3,"354,109,1141,","0,354,463,","11873,12612,13220,"
1,585,1419,21,0,0,0,0,2,1048,+,...,0,1440,chr1,248956422,11873,14361,3,"354,127,959,","0,354,481,","11873,12594,13402,"
2,585,1533,12,0,0,0,0,4,944,+,...,0,1545,chr1,248956422,11873,14362,5,"354,52,436,299,404,","0,354,406,842,1141,","11873,12645,13220,13658,13958,"
3,585,1578,27,0,0,0,0,2,884,+,...,0,1605,chr1,248956422,11873,14362,3,"354,109,1142,","0,354,463,","11873,12612,13220,"
4,585,1652,0,0,0,0,0,2,884,+,...,0,1652,chr1,248956422,11873,14409,3,"354,109,1189,","0,354,463,","11873,12612,13220,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10489974,587,298,4,0,0,0,0,0,0,-,...,0,302,chr2_KQ031384v1_fix,481245,353604,353906,1,"302,","34,","353604,"
10489975,587,272,4,0,0,0,0,0,0,-,...,8,284,chr2_KQ031384v1_fix,481245,376827,377103,1,"276,","37,","376827,"
10489976,588,280,7,0,0,0,0,0,0,-,...,0,287,chr2_KQ031384v1_fix,481245,428448,428735,1,"287,","34,","428448,"
10489977,588,283,3,0,0,0,0,0,0,-,...,0,286,chr2_KQ031384v1_fix,481245,428449,428735,1,"286,","35,","428449,"
10489978,703,2427,0,0,0,0,0,10,17028,-,...,0,2427,chrX,156040895,15560965,15580420,11,"1048,195,117,101,59,173,123,99,145,227,140,","0,1048,1243,1360,1461,1520,1693,1816,1915,2060...","15560965,15564023,15566252,15567725,15570294,1..."

In [13]:
mrna.qName

0           AM992877
1           AM992881
2           AM992878
3           AM992879
4           AM992871
              ...
10489974    MT594084
10489975    MT594083
10489976    MT594099
10489977    MT594100
10489978    MT505392
Name: qName, Length: 10489979, dtype: object

In [15]:
exon_iter = bf.read_parquet(data_path+'GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_exon_reads.parquet', iterator=True)

In [17]:
help(exon_iter)

Help on ParquetFileIterator in module bioframe.io.fileops object:

class ParquetFileIterator(pyarrow.parquet.ParquetFile)
 |  ParquetFileIterator(source, metadata=None, common_metadata=None, read_dictionary=None, memory_map=False, buffer_size=0, pre_buffer=False, coerce_int96_timestamp_unit=None)
 |
 |  Reader interface for a single Parquet file.
 |
 |  Parameters
 |  ----------
 |  source : str, pathlib.Path, pyarrow.NativeFile, or file-like object
 |      Readable source. For passing bytes or buffer-like file containing a
 |      Parquet file, use pyarrow.BufferReader.
 |  metadata : FileMetaData, default None
 |      Use existing metadata object, rather than reading from file.
 |  common_metadata : FileMetaData, default None
 |      Will be used in reads for pandas schema metadata if not found in the
 |      main file's metadata, no other uses at the moment.
 |  memory_map : bool, default False
 |      If the source is a file path, use a memory map to read file, which can
 |      improve performance in some environments.
 |  buffer_size : int, default 0
 |      If positive, perform read buffering when deserializing individual
 |      column chunks. Otherwise IO calls are unbuffered.
 |  pre_buffer : bool, default False
 |      Coalesce and issue file reads in parallel to improve performance on
 |      high-latency filesystems (e.g. S3). If True, Arrow will use a
 |      background I/O thread pool.
 |  read_dictionary : list
 |      List of column names to read directly as DictionaryArray.
 |  coerce_int96_timestamp_unit : str, default None.
 |      Cast timestamps that are stored in INT96 format to a particular
 |      resolution (e.g. 'ms'). Setting to None is equivalent to 'ns'
 |      and therefore INT96 timestamps will be infered as timestamps
 |      in nanoseconds.
 |
 |  Method resolution order:
 |      ParquetFileIterator
 |      pyarrow.parquet.ParquetFile
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __iter__(self)
 |
 |  __next__(self)
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from pyarrow.parquet.ParquetFile:
 |
 |  __init__(self, source, metadata=None, common_metadata=None, read_dictionary=None, memory_map=False, buffer_size=0, pre_buffer=False, coerce_int96_timestamp_unit=None)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  iter_batches(self, batch_size=65536, row_groups=None, columns=None, use_threads=True, use_pandas_metadata=False)
 |      Read streaming batches from a Parquet file
 |
 |      Parameters
 |      ----------
 |      batch_size : int, default 64K
 |          Maximum number of records to yield per batch. Batches may be
 |          smaller if there aren't enough rows in the file.
 |      row_groups : list
 |          Only these row groups will be read from the file.
 |      columns : list
 |          If not None, only these columns will be read from the file. A
 |          column name may be a prefix of a nested field, e.g. 'a' will select
 |          'a.b', 'a.c', and 'a.d.e'.
 |      use_threads : boolean, default True
 |          Perform multi-threaded column reads.
 |      use_pandas_metadata : boolean, default False
 |          If True and file has custom pandas schema metadata, ensure that
 |          index columns are also loaded.
 |
 |      Returns
 |      -------
 |      iterator of pyarrow.RecordBatch
 |          Contents of each batch as a record batch
 |
 |  read(self, columns=None, use_threads=True, use_pandas_metadata=False)
 |      Read a Table from Parquet format,
 |
 |      Parameters
 |      ----------
 |      columns : list
 |          If not None, only these columns will be read from the file. A
 |          column name may be a prefix of a nested field, e.g. 'a' will select
 |          'a.b', 'a.c', and 'a.d.e'.
 |      use_threads : bool, default True
 |          Perform multi-threaded column reads.
 |      use_pandas_metadata : bool, default False
 |          If True and file has custom pandas schema metadata, ensure that
 |          index columns are also loaded.
 |
 |      Returns
 |      -------
 |      pyarrow.table.Table
 |          Content of the file as a table (of columns).
 |
 |  read_row_group(self, i, columns=None, use_threads=True, use_pandas_metadata=False)
 |      Read a single row group from a Parquet file.
 |
 |      Parameters
 |      ----------
 |      i : int
 |          Index of the individual row group that we want to read.
 |      columns : list
 |          If not None, only these columns will be read from the row group. A
 |          column name may be a prefix of a nested field, e.g. 'a' will select
 |          'a.b', 'a.c', and 'a.d.e'.
 |      use_threads : bool, default True
 |          Perform multi-threaded column reads.
 |      use_pandas_metadata : bool, default False
 |          If True and file has custom pandas schema metadata, ensure that
 |          index columns are also loaded.
 |
 |      Returns
 |      -------
 |      pyarrow.table.Table
 |          Content of the row group as a table (of columns)
 |
 |  read_row_groups(self, row_groups, columns=None, use_threads=True, use_pandas_metadata=False)
 |      Read a multiple row groups from a Parquet file.
 |
 |      Parameters
 |      ----------
 |      row_groups : list
 |          Only these row groups will be read from the file.
 |      columns : list
 |          If not None, only these columns will be read from the row group. A
 |          column name may be a prefix of a nested field, e.g. 'a' will select
 |          'a.b', 'a.c', and 'a.d.e'.
 |      use_threads : bool, default True
 |          Perform multi-threaded column reads.
 |      use_pandas_metadata : bool, default False
 |          If True and file has custom pandas schema metadata, ensure that
 |          index columns are also loaded.
 |
 |      Returns
 |      -------
 |      pyarrow.table.Table
 |          Content of the row groups as a table (of columns).
 |
 |  scan_contents(self, columns=None, batch_size=65536)
 |      Read contents of file for the given columns and batch size.
 |
 |      Notes
 |      -----
 |      This function's primary purpose is benchmarking.
 |      The scan is executed on a single thread.
 |
 |      Parameters
 |      ----------
 |      columns : list of integers, default None
 |          Select columns to read, if None scan all columns.
 |      batch_size : int, default 64K
 |          Number of rows to read at a time internally.
 |
 |      Returns
 |      -------
 |      num_rows : number of rows in file
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from pyarrow.parquet.ParquetFile:
 |
 |  metadata
 |
 |  num_row_groups
 |
 |  schema
 |      Return the Parquet schema, unconverted to Arrow types
 |
 |  schema_arrow
 |      Return the inferred Arrow schema, converted from the whole Parquet
 |      file's schema
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from pyarrow.parquet.ParquetFile:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)

In [ ]:
for i, exon in enumerate(exon_iter):
#     if i > 2:
#         break
    print(i)

In [12]:
pd.read_parquet(data_path+'GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_exon_reads.parquet')

KeyboardInterrupt: